/**
 * Shared Test Factories
 * Provides type-complete mock objects for all test files.
 * Update THIS file when the Screenplay interface changes.
 */

import type { Screenplay } from '@/types';

/**
 * Creates a fully type-complete Screenplay mock.
 * Every required field is populated — override only what your test cares about.
 */
export function createTestScreenplay(overrides: Partial<Screenplay> = {}): Screenplay {
    const weightedScore = overrides.weightedScore ?? 7.5;
    const recommendation = overrides.recommendation ?? 'recommend';
    return {
        id: 'test-id',
        title: 'Test Screenplay',
        author: 'Test Author',
        logline: 'A gripping tale that tests our components.',
        genre: 'Drama',
        subgenres: ['Indie'],
        themes: ['Identity', 'Family'],
        tone: 'Atmospheric',
        collection: '2020 Black List',
        sourceFile: 'test.pdf',
        projectId: 'test-project',
        latestVersionId: 'test-version-v9',
        analysisModel: 'claude-sonnet-4-5-20250929',
        analysisVersion: 'v9_archaeology',
        producerProjection: {
            rawScore: weightedScore,
            finalScore: weightedScore,
            scoreSource: 'adjusted',
            penaltyApplied: 0,
            reportedPenalty: 0,
            finalVerdict: recommendation,
            verdictAdjustments: [],
            gates: [],
            warnings: [],
            rankable: true,
            trustStatus: 'verified',
            trustManifestVersion: 'lemon-trust-manifest-v6',
            boundary: {
                checked: false,
                runCount: 0,
                failedRunCount: 0,
                scoreSpread: 0,
                verdicts: [],
                stable: true,
            },
            readerDisagreementCount: 0,
        },
        weightedScore,
        cvsTotal: 12,
        recommendation,
        recommendationRationale: 'Strong execution with clear market potential.',
        verdictStatement: 'A solid screenplay with potential.',
        isFilmNow: false,
        filmNowAssessment: null,
        marketability: 'medium',
        budgetCategory: 'low',
        budgetJustification: 'Single location, small cast.',
        dimensionScores: {
            concept: 7,
            structure: 7,
            protagonist: 8,
            supportingCast: 7,
            dialogue: 6,
            genreExecution: 7,
            originality: 8,
            weightedScore: 7.5,
        },
        dimensionJustifications: {
            concept: 'Original premise with strong hook.',
            structure: 'Well-paced three-act structure.',
            protagonist: 'Complex, compelling lead character.',
            supportingCast: 'Solid ensemble cast.',
            dialogue: 'Natural and character-specific.',
            genreExecution: 'Meets genre expectations well.',
            originality: 'Fresh take on familiar territory.',
        },
        commercialViability: {
            targetAudience: { score: 2, note: 'Good audience' },
            highConcept: { score: 2, note: 'Solid concept' },
            castAttachability: { score: 2, note: 'Castable' },
            marketingHook: { score: 2, note: 'Has hook' },
            budgetReturnRatio: { score: 2, note: 'Good ratio' },
            comparableSuccess: { score: 2, note: 'Has comps' },
            cvsTotal: 12,
            cvsAssessed: true,
        },
        producerMetrics: {
            marketPotential: 7,
            marketPotentialRationale: 'Strong high-concept premise with proven genre appeal.',
            uspStrength: 'Moderate',
            uspStrengthRationale: 'Decent originality but familiar territory.',
        },
        criticalFailures: [],
        criticalFailureDetails: [],
        criticalFailureTotalPenalty: 0,
        majorWeaknesses: [],
        strengths: ['Strong characters', 'Unique voice'],
        weaknesses: ['Pacing issues'],
        developmentNotes: ['Polish dialogue'],
        characters: {
            protagonist: 'Jane',
            antagonist: 'Mr. Black',
            supporting: ['Ally', 'Mentor'],
        },
        structureAnalysis: {
            formatQuality: 'professional',
            actBreaks: 'Classic three-act',
            pacing: 'Tight',
        },
        comparableFilms: [
            { title: 'Film A', similarity: 'Tone', boxOfficeRelevance: 'success' },
        ],
        standoutScenes: [
            { scene: 'Opening sequence', why: 'Sets tone perfectly' },
        ],
        targetAudience: {
            primaryDemographic: '25-45 M/F',
            genderSkew: 'neutral',
            interests: ['character dramas'],
        },
        metadata: {
            filename: 'test.pdf',
            pageCount: 110,
            wordCount: 20000,
        },
        tmdbStatus: null,
        ...overrides,
    } as Screenplay;
}

export function createCoverageTestScreenplay(overrides: Partial<Screenplay> = {}): Screenplay {
    return createTestScreenplay({
        id: 'coverage-test-id',
        projectId: 'coverage-test-project',
        title: 'Matadero',
        latestVersionId: undefined,
        analysisVersion: 'coverage_v1',
        analysisModel: 'claude-sonnet-4-6',
        weightedScore: 0,
        cvsTotal: 0,
        recommendation: 'recommend',
        logline: 'A slaughterhouse worker must expose the family business before it consumes him.',
        strengths: ['A specific, cinematic world.', 'A protagonist under credible pressure.'],
        weaknesses: ['The middle repeats the same threat.'],
        majorWeaknesses: [],
        developmentNotes: ['Compress the middle and force the decisive betrayal earlier.'],
        characters: {
            protagonist: 'Mateo',
            antagonist: 'The family business',
            supporting: ['Lucia'],
        },
        dimensionScores: {
            concept: 0,
            structure: 0,
            protagonist: 0,
            supportingCast: 0,
            dialogue: 0,
            genreExecution: 0,
            originality: 0,
            weightedScore: 0,
        },
        dimensionJustifications: {
            concept: '',
            structure: '',
            protagonist: '',
            supportingCast: '',
            dialogue: '',
            genreExecution: '',
            originality: '',
        },
        commercialViability: {
            targetAudience: { score: 0, note: '' },
            highConcept: { score: 0, note: '' },
            castAttachability: { score: 0, note: '' },
            marketingHook: { score: 0, note: '' },
            budgetReturnRatio: { score: 0, note: '' },
            comparableSuccess: { score: 0, note: '' },
            cvsTotal: 0,
            cvsAssessed: false,
        },
        producerProjection: {
            rawScore: 0,
            finalScore: 0,
            scoreSource: 'coverage_unscored',
            penaltyApplied: 0,
            reportedPenalty: 0,
            finalVerdict: 'recommend',
            verdictAdjustments: [],
            gates: [],
            warnings: [],
            rankable: false,
            trustStatus: 'incomplete',
            boundary: {
                checked: false,
                runCount: 0,
                failedRunCount: 0,
                scoreSpread: 0,
                verdicts: [],
                stable: true,
            },
            readerDisagreementCount: 0,
        },
        coverage: {
            status: 'sealed',
            verdict: 'RECOMMEND',
            confidence: 'high',
            engineVersion: 'coverage-v1.1',
            synopsis: 'Mateo discovers that the family slaughterhouse conceals a larger crime.',
            want: 'Protect Lucia and leave the business.',
            need: 'Choose truth over family loyalty.',
            stakes: 'Lucia dies and Mateo becomes complicit.',
            climax: 'Mateo records his father confessing on the kill floor.',
            ending: 'He sends the recording, then walks into police custody.',
            majorTurns: [{ turn: 'Mateo finds the hidden ledger.', page: 28 }],
            championReason: 'The world, moral pressure, and ending create a producible thriller.',
            passReason: 'The repeated middle could flatten the escalation.',
            commercialHypothesis: 'A contained Spanish-language thriller with a strong hook.',
            supportRate: 1,
            citationsVerified: 12,
            citationsTotal: 12,
            pageConvention: 'Printed screenplay pages.',
        },
        lensGrades: [
            { lens: 'Lemon Coverage', grade: 'strong', note: 'The moral choice lands clearly.' },
            { lens: 'Story Grid', grade: 'solid', note: 'The escalation is mostly coherent.' },
        ],
        continuityFlags: ['Mateo is called the older and younger brother in separate scenes.'],
        reviewReasons: ['Confirm the birth-order contradiction before development.'],
        uncertainties: ['The exact age gap is not stated.'],
        humanReviewRecommended: true,
        ...overrides,
    });
}
